from django.urls import path
from .views import *

administrator_urls = [
    path('administrator/', dashboard, name='dashboard'),
    path('administrator/admitted-patient/', admitted_patient, name='admitted_patient'),
    path('administrator/outpatient/patient/',
         outpatient_patient, name='outpatient_patient'),
    path('administrator/report/', report, name='report'),
    path('administrator/complaints/', complaints, name='complaints'),
    path('administrator/medication-completed/',
         medication_completed, name='medication_completed'),
    path('administrator/medication-request/',
         medication_request, name='medication_request'),
    path('administrator/medication-new/',
         medication_new, name='medication_new'),
    path('administrator/imaging-completed/', imaging_completed, name='imaging_completed'),
    path('administrator/imaging-request/', imaging_request, name='imaging_request'),
    path('administrator/all-schedule/', all_schedule, name='all_schedule'),
    path('administrator/today-schedule/', today_schedule, name='today_schedule'),
    path('administrator/add-schedule/', add_schedule, name='add_schedule'),
    path('administrator/theater-schedule/', theater_schedule, name='theater_schedule'),
    path('administrator/add-theater-schedule/',
         add_theater_schedule, name='add_theater_schedule'),
    path('administrator/lab-new/', lab_new, name='lab_new'),
    path('administrator/lab-request/', lab_request, name='lab_request'),
    path('administrator/lab-completed/', lab_completed, name='lab_completed'),
    path('administrator/invoice/', invoice, name='invoice'),
    path('administrator/new-invoice/', new_invoice, name='new_invoice'),
    path('administrator/price/', price, name='price'),
    path('administrator/price-profile/', price_profile, name='price_profile'),
    path('administrator/new-incident/', new_incident, name='new_incident'),
    path('administrator/current-incident/', current_incident, name='current_incident'),
    path('administrator/report-incident/', report_incident, name='report_incident'),
    path('administrator/history-incident/', history_incident, name='history_incident'),
]
